language: rust
rust:
- stable

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgtk-3-dev libglib2.0-dev libcairo2-dev libpango1.0-dev libatk1.0-dev libgdk-pixbuf2.0-dev

script:
- cargo build
- cargo test
- cargo build --features "with-titik"
- cargo build --features "with-web"
- cargo build --features "with-gtk"
