[package]
name = "sauron-widget"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expanse = { version = "0.3"}
mt-dom = { version = "0.6" }
